### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ysq1051838264** [linwh1115/react-native-cnodejs#9]
Error: Cannot find module 'lodash/object/assign'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/rn project/react-native-cnodejs/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/Volumes/rn project/react-native-cnodejs/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/rn project/react-native-cnodejs/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:573:32)

**Comment by whlin1115** [comment]
@ysq1051838264  使用yarn安装依赖，node版本8.1
